const actions = {
  FETCH_JOBS_SUCCESS: 'FETCH_JOBS_SUCCESS',
  FETCH_JOBS_FAIL: 'FETCH_JOBS_FAIL',
  FETCH_JOB_SUCCESS: 'FETCH_JOB_SUCCESS',
  FETCH_JOB_FAIL: 'FETCH_JOB_FAIL',
  FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',
  FETCH_EVENTS_FAIL: 'FETCH_EVENTS_FAIL',
  FETCH_EVENT_SUCCESS: 'FETCH_EVENT_SUCCESS',
  FETCH_EVENT_FAIL: 'FETCH_EVENT_FAIL',
  FETCH_NEWS_SUCCESS: 'FETCH_NEWS_SUCCESS',
  FETCH_NEWS_FAIL: 'FETCH_NEWS_FAIL',
  FETCH_NEWS_ITEM_SUCCESS: 'FETCH_NEWS_ITEM_SUCCESS',
  FETCH_NEWS_ITEM_FAIL: 'FETCH_NEWS_ITEM_FAIL',
};

export default actions;
